#!/usr/bin/env node
/**
 * Post-build script that converts the TanStack Start SSR output
 * (`dist/client` + `dist/server`) into a fully static site at
 * `dist/static/` suitable for cPanel / Apache / any static host.
 *
 * - Invokes the cloudflare-module SSR handler in-process (Node 22+ has
 *   fetch/Request/Response) to prerender every listed public route.
 * - Writes <route>/index.html for each route, plus sitemap.xml & robots.txt.
 * - Copies all client assets (JS / CSS / images / fonts / favicon).
 * - Generates an .htaccess for clean URL routing.
 *
 * Run automatically after `npm run build` via the `postbuild` script.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const clientDir = path.join(root, "dist/client");
const serverEntry = path.join(root, "dist/server/index.mjs");
const outDir = path.join(root, "dist/static");

// Every public route from src/routes/ (page routes + sitemap/robots).
const PAGE_ROUTES = [
  "/",
  "/about",
  "/audits",
  "/brand-guidelines",
  "/changelog",
  "/compare",
  "/contact",
  "/cookies",
  "/docs",
  "/documentation",
  "/ecosystem",
  "/privacy",
  "/releases",
  "/roadmap",
  "/security",
  "/terms",
];
const EXTRA_ROUTES = [
  { path: "/sitemap.xml", file: "sitemap.xml" },
];

async function rimraf(p) {
  await fs.rm(p, { recursive: true, force: true });
}
async function copyDir(src, dst) {
  await fs.mkdir(dst, { recursive: true });
  for (const entry of await fs.readdir(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) await copyDir(s, d);
    else await fs.copyFile(s, d);
  }
}

async function main() {
  // Sanity check
  for (const p of [clientDir, serverEntry]) {
    try { await fs.access(p); }
    catch {
      console.error(`[build-static] Missing ${p}. Did 'vite build' run?`);
      process.exit(1);
    }
  }

  console.log("[build-static] Preparing dist/static/");
  await rimraf(outDir);
  await fs.mkdir(outDir, { recursive: true });

  // 1. Copy all client assets (JS, CSS, images, fonts, favicon, robots.txt…)
  console.log("[build-static] Copying client assets…");
  await copyDir(clientDir, outDir);
  // _headers is a Cloudflare Pages file — useless on Apache. Remove it.
  await rimraf(path.join(outDir, "_headers"));

  // 2. Load SSR handler and prerender each route
  console.log("[build-static] Loading SSR handler…");
  const mod = await import(pathToFileURL(serverEntry).href);
  const handler = mod.default ?? mod;
  const env = { ASSETS: { fetch: () => new Response(null, { status: 404 }) } };
  const ctx = { waitUntil: () => {}, passThroughOnException: () => {} };

  async function render(routePath) {
    const url = `http://localhost${routePath}`;
    const res = await handler.fetch(new Request(url), env, ctx);
    if (res.status >= 400) {
      throw new Error(`Render failed for ${routePath} (HTTP ${res.status})`);
    }
    return await res.text();
  }

  for (const route of PAGE_ROUTES) {
    process.stdout.write(`[build-static] Prerender ${route} … `);
    const html = await render(route);
    const dirPath = route === "/" ? outDir : path.join(outDir, route);
    await fs.mkdir(dirPath, { recursive: true });
    await fs.writeFile(path.join(dirPath, "index.html"), html, "utf8");
    console.log("ok");
  }

  for (const extra of EXTRA_ROUTES) {
    process.stdout.write(`[build-static] Prerender ${extra.path} … `);
    const body = await render(extra.path);
    await fs.writeFile(path.join(outDir, extra.file), body, "utf8");
    console.log("ok");
  }

  // 3. .htaccess for clean URLs + SPA fallback to index.html for unknown routes
  const htaccess = `# Generated by scripts/build-static.mjs
Options -MultiViews
DirectoryIndex index.html

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Serve existing files/directories directly (assets, images, fonts, etc.)
  RewriteCond %{REQUEST_FILENAME} -f [OR]
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteRule ^ - [L]

  # Clean URL: /about -> /about/index.html when that file exists
  RewriteCond %{DOCUMENT_ROOT}/$1/index.html -f
  RewriteRule ^(.+?)/?$ /$1/index.html [L]

  # SPA fallback: anything else goes to root index.html (client router handles it)
  RewriteRule ^ /index.html [L]
</IfModule>

# Long-term cache for hashed asset bundles
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css "access plus 1 year"
  ExpiresByType application/javascript "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 year"
  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType font/woff2 "access plus 1 year"
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\\.(?:js|css|woff2?|ttf|otf|eot|png|jpg|jpeg|svg|webp|ico)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.html$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>
</IfModule>
`;
  await fs.writeFile(path.join(outDir, ".htaccess"), htaccess, "utf8");
  console.log("[build-static] Wrote .htaccess");

  console.log(`\n[build-static] Done. Static site at: ${path.relative(root, outDir)}/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
