/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BrandGuidelinesRouteImport } from './routes/brand-guidelines'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandGuidelinesRoute = BrandGuidelinesRouteImport.update({
  id: '/brand-guidelines',
  path: '/brand-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audits': typeof AuditsRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/documentation': typeof DocumentationRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audits': typeof AuditsRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/documentation': typeof DocumentationRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audits': typeof AuditsRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/documentation': typeof DocumentationRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audits'
    | '/brand-guidelines'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/documentation'
    | '/ecosystem'
    | '/privacy'
    | '/releases'
    | '/roadmap'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audits'
    | '/brand-guidelines'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/documentation'
    | '/ecosystem'
    | '/privacy'
    | '/releases'
    | '/roadmap'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audits'
    | '/brand-guidelines'
    | '/changelog'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/documentation'
    | '/ecosystem'
    | '/privacy'
    | '/releases'
    | '/roadmap'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditsRoute: typeof AuditsRoute
  BrandGuidelinesRoute: typeof BrandGuidelinesRoute
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRoute
  DocumentationRoute: typeof DocumentationRoute
  EcosystemRoute: typeof EcosystemRoute
  PrivacyRoute: typeof PrivacyRoute
  ReleasesRoute: typeof ReleasesRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-guidelines': {
      id: '/brand-guidelines'
      path: '/brand-guidelines'
      fullPath: '/brand-guidelines'
      preLoaderRoute: typeof BrandGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditsRoute: AuditsRoute,
  BrandGuidelinesRoute: BrandGuidelinesRoute,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRoute,
  DocumentationRoute: DocumentationRoute,
  EcosystemRoute: EcosystemRoute,
  PrivacyRoute: PrivacyRoute,
  ReleasesRoute: ReleasesRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
